### PR TITLE
Add DoNotHashLeaves config

### PR DESCRIPTION
**Pull request by alrevuelta**
- [x] Add a new configuration flag `DoNotHashLeaves` to avoid hashing the leafs of the tree. This is specifically useful when the input to the tree (leafs) were already concatenated/hashed in a different way that differs from the `HashFunc`.
- [x] Add tests to the new feature.

### CODE REVIEW

**Comment by alrevuelta** [comment]
If you think this feature is relevant for the repo, I can add test.

**Comment by txaty** [comment]
Thanks for contributing. This is a very good feature to add. Would you please add some unit tests to it?

**Comment by alrevuelta** [comment]
@txaty Done!

**Comment by txaty** [comment]
LGTM

**Pull request merged**
